### ISSUE TITLE
Analyze failures

### ISSUE THREAD

**Issue by charmoniumQ** [charmoniumQ/EDGAR-research#2]
Look at some of the companies that the parser chokes on. Pass the names to me. Try to identify the cause, if possible.

**Comment by RationalActor** [comment]
some of the files don't have risk factors (smaller reporting companies are not always required to report them). I have copied the formatting of the table of contents from the raw text file (just the stuff in the neighborhood of the 1A risk factor entry) if it seemed like it was out of the ordinary.

[failure analysis seeligson results.txt](https://github.com/charmoniumQ/EDGAR-research/files/752720/failure.analysis.seeligson.results.txt)
