### ISSUE TITLE
Find stop words

### ISSUE THREAD

**Issue by charmoniumQ** [charmoniumQ/EDGAR-research#9]

**Comment by smonadjemi** [comment]
MALLET seems to have an option to `--remove-stopwords` when it imports data.

**Comment by charmoniumQ** [comment]
Clustering works better in less dimensions (see curse of dimensionality), so even after removing stop words, I want to remove more words (dimensions). This could be good http://scikit-learn.org/stable/modules/feature_selection.html#univariate-feature-selection
